version: '3'
services:
  kong_database:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    restart: on-failure
  kong:
    image: kong
    command: kong start --run-migrations
    depends_on:
      - kong_database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong_database
      - KONG_PG_DATABASE=kong
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    ports:
      - "8000:8000"
      - "8443:8443"
    restart: on-failure
  konga:
    image: pantsel/konga
    depends_on:
      - kong
    environment:
      - NODE_ENV=production
    ports: 
      - 1337:1337
  frp_server:
    image: geektr/frp
    restart: always
    env_file:
      - "$secrets_dir/frp/frp.env"
    volumes:
      - "$service_dir/conf/frp/frps.ini:/etc/frp/frps.ini:ro"
    ports: 
      - "7000:7000"
      - "7001:7001"
